# fly.toml app configuration file generated for soften65x66 on 2023-07-22T18:34:07+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "soften65x66"
primary_region = "sin"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
